#!/usr/bin/env python3
"""Shared model-architecture profiles for the packing scripts.

The C engine gets its constants from metal_infer/arch*.h; the Python side
gets them from here. Both derive the packed expert layout from the same three
numbers (hidden size, expert intermediate size, quantization group size), so
they cannot disagree about byte offsets.

A profile generated by gen_arch_header.py is picked up automatically: if
metal_infer/<name>.json exists it overrides the built-in defaults.
"""

import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))

# Built-in profiles. `expert_pattern` is a regex over safetensors tensor names
# with two groups: layer index and component.
BUILTIN = {
    "qwen35_moe": {
        "name": "Qwen3.5-397B-A17B",
        "num_layers": 60,
        "num_experts": 512,
        "hidden": 4096,
        "moe_intermediate": 1024,
        "group_size": 64,
        "bits": 4,
        "expert_pattern":
            r'^language_model\.model\.layers\.(\d+)\.mlp\.switch_mlp\.'
            r'((?:gate|up|down)_proj\.(?:weight|scales|biases))$',
    },
    "laguna_s": {
        # Real values from poolside's config.json (docs/laguna_s_2.1_config.json).
        # Layer 0 is a dense MLP, so only layers 1..47 carry routed experts.
        "name": "Laguna-S-2.1",
        "num_layers": 48,
        "num_experts": 256,
        "hidden": 3072,
        "moe_intermediate": 1024,
        "group_size": 64,
        "bits": 4,
        "dense_layers": [0],
        # mlx-lm fuses the routed experts into a single switch_mlp tensor. The
        # optional prefix covers both plain and multimodal-style naming.
        "expert_pattern":
            r'^(?:language_model\.)?model\.layers\.(\d+)\.mlp\.switch_mlp\.'
            r'((?:gate|up|down)_proj\.(?:weight|scales|biases))$',
    },
}

DEFAULT_ARCH = "qwen35_moe"


def component_layout(hidden, moe_intermediate, group_size, bits=4):
    """Packed per-expert layout: nine blobs in a fixed order.

    Mirrors ARCH_* in metal_infer/arch.h. Weights are `bits`-bit values packed
    into uint32 words; scales and biases are bf16, one per group of inputs.
    """
    div = 8 if bits == 4 else 16 // bits * 2  # 4-bit: 8 per u32, 2-bit: 16 per u32
    if bits == 4:
        w_gate = hidden * moe_intermediate // 2
        w_down = hidden * moe_intermediate // 2
    elif bits == 2:
        w_gate = hidden * moe_intermediate // 4
        w_down = hidden * moe_intermediate // 4
    else:
        raise ValueError(f"unsupported bit width {bits}")
    del div

    s_gate = moe_intermediate * (hidden // group_size) * 2
    s_down = hidden * (moe_intermediate // group_size) * 2

    comps = []
    off = 0
    for proj, wsz, ssz, shape_w in (
        ("gate_proj", w_gate, s_gate, [moe_intermediate, hidden]),
        ("up_proj", w_gate, s_gate, [moe_intermediate, hidden]),
        ("down_proj", w_down, s_down, [hidden, moe_intermediate]),
    ):
        comps.append({"name": f"{proj}.weight", "offset": off, "size": wsz,
                      "dtype": "U32", "shape": shape_w})
        off += wsz
        comps.append({"name": f"{proj}.scales", "offset": off, "size": ssz, "dtype": "BF16"})
        off += ssz
        comps.append({"name": f"{proj}.biases", "offset": off, "size": ssz, "dtype": "BF16"})
        off += ssz
    return comps, off


def load_profile(arch=None):
    """Return a profile dict, with derived layout fields filled in."""
    arch = arch or os.environ.get("FLASH_MOE_ARCH") or DEFAULT_ARCH
    if arch not in BUILTIN:
        raise SystemExit(f"unknown arch '{arch}'; known: {', '.join(sorted(BUILTIN))}")
    p = dict(BUILTIN[arch])

    # A generated profile (from gen_arch_header.py) wins over the defaults.
    generated = os.path.join(ROOT, "metal_infer", f"arch_{arch}.json")
    if os.path.exists(generated):
        with open(generated) as f:
            p.update(json.load(f))

    comps, expert_size = component_layout(
        p["hidden"], p["moe_intermediate"], p["group_size"], p.get("bits", 4))
    p["arch"] = arch
    p["components"] = comps
    p["expert_size"] = expert_size
    p["layer_size"] = expert_size * p["num_experts"]
    return p


def describe(p):
    total = p["layer_size"] * p["num_layers"]
    return (f"{p['name']} [{p['arch']}]: {p['num_layers']} layers x {p['num_experts']} experts, "
            f"expert={p['expert_size']:,} B, layer={p['layer_size'] / 1e9:.2f} GB, "
            f"total={total / 1e9:.1f} GB")


if __name__ == "__main__":
    import sys
    for name in (sys.argv[1:] or sorted(BUILTIN)):
        print(describe(load_profile(name)))
